env:
  WAYPOINT_SERVER_TOKEN: "HZCwuUtmrrpbHmG8aC3tEkTzNGB2bjUJkpUyU1StbJgUqDBdaXuQh1rHVumo6rqakVeohzVKDEivNUJa6SzHuwe85Gch1gTB6eHgKgFkmXsSDRQkTi56WmfEacGFp3oh22kQyXLWzPCg7Arjz5qrebsJY1fpcXgQUube"
  AUTH_TOKEN: "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"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  WAYPOINT_SERVER_ADDR: waypoint.example.com:9701
  WAYPOINT_SERVER_TLS: 1
  WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1



name: 'deploy'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/action-setup-waypoint@'0.1.0'
    - run: waypoint init
    - run: waypoint build
